version: '3'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  # rust:
  #   build: ./axum
  #   restart: always
  #   depends_on:
  #     - mysql
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_PORT: 3306
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   networks:
  #     - backend

# networks:
#   backend:
